# Generated by Django 3.2.6 on 2021-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210909_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_four',
            field=models.TextField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_four_count',
            field=models.IntegerField(default=0),
        ),
    ]
